@host=http://localhost:4000

###
GET {{host}}/

###
POST {{host}}/account
Content-Type: application/json

{
    "cif_number" : "1234567890",
    "currency" : "IDR",
    "status" : "BUKA"
}

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:27:28 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 252
# Connection: close
# X-Powered-By: Express
# ETag: W/"fc-DOk/v9X7K7sdjYxOpO+oPAifZcY"

# {
#   "data": {
#     "account_number": "2300741325",
#     "currency": "IDR",
#     "balance": 0,
#     "status": "BUKA",
#     "cif_number": "1234567890",
#     "_id": "62e1e6003d74051b341497d3",
#     "createdAt": "2022-07-28T01:27:28.231Z",
#     "updatedAt": "2022-07-28T01:27:28.231Z",
#     "__v": 0
#   },
#   "elapsed_time": "19ms"
# }


###
PUT {{host}}/account/update_balance/4902265825
Content-Type: application/json

{
    "balance" : 1000
}

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:28:09 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 74
# Connection: close
# X-Powered-By: Express
# ETag: W/"4a-Qc9LPFV/zjsMeA0nXtSLY4NFFIc"

# {
#   "elapsed_time": "18ms",
#   "data": {
#     "message": "Account updated successfully!"
#   }
# }



###
PUT {{host}}/account/settlement
Content-Type: application/json

{
    "debit_account_number" : "4902265825",
    "debit_account_balance" : 700,
    "credit_account_number" : "2300741325",
    "credit_account_balance" : 300
}

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:28:43 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 74
# Connection: close
# X-Powered-By: Express
# ETag: W/"4a-3YxPL7XzqAsS2XgrWUJ9OxoFIL0"

# {
#   "elapsed_time": "16ms",
#   "data": {
#     "message": "Account updated successfully!"
#   }
# }



###
GET {{host}}/accounts/1234567890

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:28:57 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 479
# Connection: close
# X-Powered-By: Express
# ETag: W/"1df-pPWCaNSmjnL+wpt3DvwjkX4oA6g"

# {
#   "elapsed_time": "7ms",
#   "data": [
#     {
#       "_id": "62e1e6003d74051b341497d3",
#       "account_number": "2300741325",
#       "currency": "IDR",
#       "balance": 300,
#       "status": "BUKA",
#       "cif_number": "1234567890",
#       "createdAt": "2022-07-28T01:27:28.231Z",
#       "updatedAt": "2022-07-28T01:28:43.694Z",
#       "__v": 0
#     },
#     {
#       "_id": "62e1e6183d74051b341497d5",
#       "account_number": "4902265825",
#       "currency": "IDR",
#       "balance": 700,
#       "status": "BUKA",
#       "cif_number": "1234567890",
#       "createdAt": "2022-07-28T01:27:52.853Z",
#       "updatedAt": "2022-07-28T01:28:43.687Z",
#       "__v": 0
#     }
#   ]
# }

###
GET {{host}}/account/2300741325

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:29:17 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 253
# Connection: close
# X-Powered-By: Express
# ETag: W/"fd-YsCAEQPoMMou2v04X5feix0QdBs"

# {
#   "elapsed_time": "9ms",
#   "data": {
#     "_id": "62e1e6003d74051b341497d3",
#     "account_number": "2300741325",
#     "currency": "IDR",
#     "balance": 300,
#     "status": "BUKA",
#     "cif_number": "1234567890",
#     "createdAt": "2022-07-28T01:27:28.231Z",
#     "updatedAt": "2022-07-28T01:28:43.694Z",
#     "__v": 0
#   }
# }

###
PUT {{host}}/account/2300741325
Content-Type: application/json

{
    "status" : "TTUP"
}

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:29:47 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 73
# Connection: close
# X-Powered-By: Express
# ETag: W/"49-2IEmPcMnVjYdKvwBTyHwhZTWjQ4"

# {
#   "elapsed_time": "5ms",
#   "data": {
#     "message": "Account updated successfully!"
#   }
# }



###
DELETE {{host}}/account/2300741325

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:30:07 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 73
# Connection: close
# X-Powered-By: Express
# ETag: W/"49-VVyQT0eGphicWF0aslHAcKFNMFg"

# {
#   "elapsed_time": "5ms",
#   "data": {
#     "message": "Account deleted successfully!"
#   }
# }


