@host=http://localhost:4000

###
GET {{host}}/historical_transaction/1694461831/0/100

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:37:46 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 1085
# Connection: close
# X-Powered-By: Express
# ETag: W/"43d-nEku110akSAwzsH/OqS+q2KsL1A"

# {
#   "elapsed_time": "9ms",
#   "data": [
#     {
#       "_id": "62e1e83062926c47225ddef4",
#       "account_number": "1694461831",
#       "current_balance": 700,
#       "amount": 100,
#       "journal_number": "1857771513",
#       "action": "DEBIT",
#       "transaction_type": "TRANSFER",
#       "createdAt": "2022-07-28T01:36:48.122Z",
#       "updatedAt": "2022-07-28T01:36:48.122Z",
#       "__v": 0
#     },
#     {
#       "_id": "62e1e82f62926c47225ddeee",
#       "account_number": "1694461831",
#       "current_balance": 800,
#       "amount": 100,
#       "journal_number": "5464542997",
#       "action": "DEBIT",
#       "transaction_type": "TRANSFER",
#       "createdAt": "2022-07-28T01:36:47.883Z",
#       "updatedAt": "2022-07-28T01:36:47.883Z",
#       "__v": 0
#     },
#     {
#       "_id": "62e1e82d62926c47225ddee8",
#       "account_number": "1694461831",
#       "current_balance": 900,
#       "amount": 100,
#       "journal_number": "6411231757",
#       "action": "DEBIT",
#       "transaction_type": "TRANSFER",
#       "createdAt": "2022-07-28T01:36:45.373Z",
#       "updatedAt": "2022-07-28T01:36:45.373Z",
#       "__v": 0
#     },
#     {
#       "_id": "62e1e82562926c47225ddee6",
#       "account_number": "1694461831",
#       "current_balance": 1000,
#       "amount": 1000,
#       "journal_number": "3627347507",
#       "action": "CREDIT",
#       "transaction_type": "DEPOSIT",
#       "createdAt": "2022-07-28T01:36:37.893Z",
#       "updatedAt": "2022-07-28T01:36:37.893Z",
#       "__v": 0
#     }
#   ]
# }



### 
GET {{host}}/historical_transaction/5943889126/0/100