@host=http://localhost:4010

### credit 1407146532
POST {{host}}/transaction/credit
Content-Type: application/json

{
    "account_number" : "1407146532",
    "amount": 1000
}

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:31:18 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 122
# Connection: close
# X-Powered-By: Express
# ETag: W/"7a-dEoycc1gBQNAnOjhyAEUWuY8cKM"

# {
#   "elapsed_time": "49ms",
#   "data": {
#     "message": "7531095214 has been credited by 1000 successfully",
#     "journal_number": 2368854491
#   }
# }


### debit 8606011070
POST {{host}}/transaction/debit
Content-Type: application/json

{
    "account_number" : "8606011070",
    "amount": 10
}

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:31:31 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 93
# Connection: close
# X-Powered-By: Express
# ETag: W/"5d-eQlf48u1qQhwhfR+nBzBWMn8ENQ"

# {
#   "elapsed_time": "19ms",
#   "data": {
#     "message": "4902265825 has been deducted by 100 successfully"
#   }
# }


### transfer
POST {{host}}/transaction/transfer
Content-Type: application/json

{
    "cif_number": "1234567890",
    "debit_account_number" : "1407146532",
    "credit_account_number" : "8606011070",
    "amount" : 100
}

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:31:43 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 111
# Connection: close
# X-Powered-By: Express
# ETag: W/"6f-RCGp33U8mf7L7yIlB+cJv0A+bBQ"

# {
#   "elapsed_time": "45ms",
#   "data": {
#     "message": "300 has been transfered from 7531095214 to 4902265825 successfully"
#   }
# }

###
GET {{host}}/transactions/1234567890

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.23.1
# Date: Thu, 28 Jul 2022 01:36:55 GMT
# Content-Type: application/json; charset=utf-8
# Content-Length: 1082
# Connection: close
# X-Powered-By: Express
# ETag: W/"43a-n9G3SpIR1E4qVxHN1B9EfsroSdo"

# {
#   "elapsed_time": "18ms",
#   "data": [
#     {
#       "_id": "62e1e83062926c47225ddef8",
#       "cif_number": "1234567890",
#       "debit_account_number": "1694461831",
#       "debit_account_balance": 700,
#       "credit_account_number": "7834028028",
#       "credit_account_balance": 300,
#       "amount": 100,
#       "transaction_type": "TRANSFER",
#       "journal_number": "1857771513",
#       "createdAt": "2022-07-28T01:36:48.132Z",
#       "updatedAt": "2022-07-28T01:36:48.132Z",
#       "__v": 0
#     },
#     {
#       "_id": "62e1e82f62926c47225ddef2",
#       "cif_number": "1234567890",
#       "debit_account_number": "1694461831",
#       "debit_account_balance": 800,
#       "credit_account_number": "7834028028",
#       "credit_account_balance": 200,
#       "amount": 100,
#       "transaction_type": "TRANSFER",
#       "journal_number": "5464542997",
#       "createdAt": "2022-07-28T01:36:47.892Z",
#       "updatedAt": "2022-07-28T01:36:47.892Z",
#       "__v": 0
#     },
#     {
#       "_id": "62e1e82d62926c47225ddeec",
#       "cif_number": "1234567890",
#       "debit_account_number": "1694461831",
#       "debit_account_balance": 900,
#       "credit_account_number": "7834028028",
#       "credit_account_balance": 100,
#       "amount": 100,
#       "transaction_type": "TRANSFER",
#       "journal_number": "6411231757",
#       "createdAt": "2022-07-28T01:36:45.383Z",
#       "updatedAt": "2022-07-28T01:36:45.383Z",
#       "__v": 0
#     }
#   ]
# }