version: "3.7"
services:
    account:
        image: "core-sandbox_account:latest"
        environment: 
            MONGODB_HOST: mongodb://192.168.160.138:5000/core-sandbox
        ports:
            - "4000:3000"
    transaction:
        image: "core-sandbox_transaction:latest"
        environment: 
            MONGODB_HOST: mongodb://192.168.160.138:5000/core-sandbox
            ACCOUNT_HOST: http://account:3000
        ports:
            - "4010:3000"
    historical_transaction:
        image: "core-sandbox_historical_transaction:latest"
        environment: 
            MONGODB_HOST: mongodb://192.168.160.138:5000/core-sandbox
        ports:
            - "4020:3000"